#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
npm run lint
npm test

echo -e "===\n>> Talenavi Pre-commit Hook:: Checking branch name / Mengecek nama branch..."
branchName=$(git branch | grep '*' | sed 's/* //')

if [ $branchName == 'main' ]
then
  echo -e "\n🚫 Commit directly to master branch is not allowed! / Commit langsung ke branch master dilarang!\n" && exit 1
fi
